return {
  diagnostics = {
    Error = " ",
    Warn = " ",
    Hint = " ",
    Info = " ",
  },
  git = {
    Added = " ",
    Modified = " ",
    Removed = " ",
    Branch = " ",
  },
  ui = {
    VimIcon = "",
    FolderClosed = " ",
    FolderOpen = " ",
    LspLoaded = " ",
    LspLoading = {
      "⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏",
    },
  },
  modes = {
    n = { name = "NORMAL", color = "#7AA2F7" },
    no = { name = "OP", color = "#7AA2F7" },
    v = { name = "VISUAL", color = "#BB9AF7" },
    V = { name = "V-LINE", color = "#BB9AF7" },
    ["\22"] = { name = "V-BLOCK", color = "#BB9AF7" },
    s = { name = "SELECT", color = "#BB9AF7" },
    S = { name = "S-LINE", color = "#BB9AF7" },
    ["\19"] = { name = "S-BLOCK", color = "#BB9AF7" },
    i = { name = "INSERT", color = "#9ECE6A" },
    ic = { name = "INSERT", color = "#9ECE6A" },
    ix = { name = "INSERT", color = "#9ECE6A" },
    R = { name = "REPLACE", color = "#F7768E" },
    Rc = { name = "REPLACE", color = "#F7768E" },
    Rx = { name = "REPLACE", color = "#F7768E" },
    Rv = { name = "V-REPLACE", color = "#F7768E" },
    Rvc = { name = "V-REPLACE", color = "#F7768E" },
    Rvx = { name = "V-REPLACE", color = "#F7768E" },
    c = { name = "COMMAND", color = "#E0AF68" },
    cv = { name = "EX", color = "#E0AF68" },
    ce = { name = "EX", color = "#E0AF68" },
    r = { name = "PROMPT", color = "#E0AF68" },
    rm = { name = "MORE", color = "#E0AF68" },
    ["r?"] = { name = "CONFIRM", color = "#E0AF68" },
    ["!"] = { name = "SHELL", color = "#F7768E" },
    t = { name = "TERMINAL", color = "#F7768E" },
  },
}
