-- Customize Transparent plugins

return {
  -- Configuration in /lua/plugins/astrocore.lua file
  "xiyaowong/transparent.nvim",
  name = "transparent",
  event = "User AstroFile",
  config = function()
    vim.g.transparent_groups = vim.list_extend(vim.g.transparent_groups or {}, {
      "CmpBorder",
      "CmpDoc",
      "CmpPmenu",
      "DapUINormalNC",
      "DapUIPlayPauseNC",
      "DapUIRestartNC",
      "DapUIStepBackNC",
      "DapUIStepIntoNC",
      "DapUIStepOutNC",
      "DapUIStepOverNC",
      "DapUIStopNC",
      "DapUIUnavailableNC",
      "FloatBorder",
      "FoldColumn",
      "HeirlineCommand",
      "HeirlineInactive",
      "HeirlineInsert",
      "HeirlineNormal",
      "HeirlineReplace",
      "HeirlineTerminal",
      "HeirlineVisual",
      "NeoTree",
      "NeoTreeFloatNormal",
      "NeoTreeNormal",
      "NeoTreeNormalNC",
      "NeoTreeTabInactive",
      "NeoTreeTabSeparatorInactive",
      "NeoTreeVertSplit",
      "NeoTreeWinSeparator",
      "NormalFloat",
      "StatusLine",
      "TabLine",
      "TabLineFill",
      "TabLineSel",
      "WinBar",
      "WinBarNC",
    })
  end,
}
